### PR TITLE
Rename pct_complete to percent_complete

### PR DESCRIPTION
**Pull request by Silex**
`pct_complete` is a poor name.

I was also tempted to rename it to `percent` but I think the `_complete` part is important.

### CODE REVIEW

**Comment by utgarda** [comment]
Hi @Silex ! Thanks for pointing that out, I agree - this is definitely not the best naming practice. Not that I feel ashamed of it or anything :) But I'd better not introduce a non-backwards-compatible change just for the sake of code style. While this is a great prettification job, it may cost someone 5 or more quite unpleasant minutes.

**Comment by Silex** [comment]
Weird because you merged #22

Anyway, maybe you could simply add an `alias :pct_complete :percent_complete` and deprecate pct_complete with http://docs.ruby-lang.org/en/2.1.0/Gem/Deprecate.html

**Comment by utgarda** [comment]
Nice idea, will do exactly that!

**Comment by utgarda** [comment]
And yeah, the #22 contained a more urgent renaming, IMO :)

**Pull request closed without merging**
