### PR TITLE
As collection feature

### PR DESCRIPTION
**Pull request by mpospelov**
Add as collection feature to allow working with sidekiq workers like with ActiveRecord collection. 

I find it very useful to track all statuses at once but it's not possible when you have a thousands of small jobs running. So in order to paginate the collection and sort by `update_time` I decided to add this feature.

### CODE REVIEW

**Comment by kenaniah** [comment]
Closing in favor of #118

**Comment by mpospelov** [comment]
Hi @kenaniah . 
These 2 PRs are following 2 different tasks, this PR is for working with big collections as everything happens on Redis side. 
#118 solves the sidekiq-status web-client problem but doing everything in ruby so it will be slow.
Let me explain in details

**Given:** 

1. Array of 30000 status
2. You need to access 15000-15100 slice of data and sort it by created_at

**#118 approach:**

1. Loads 30000 statuses from Redis - Network heavy
2. Sort them in ruby - ruby is not super fast but it's ok to sort such amount
3. Access 1500-15100 slice - simple and fast

**My approach** is to use built-in Redis [set structure](https://redis.io/commands/sadd)  (it's like an index in SQL database) to manipulate with data fast:

1. Sort and slice collection just in Redis with [SORT](https://redis.io/commands/sort)
2. Load just 100 elements already sorted and sliced from Redis

Conclusions:
Bigger array, bigger win with this PR approach.
The only thing is that it will lose some performance on write-heavy system, but I don't think it will be noticeable as `SADD` O(1) complexity

I don't have any changes applied to sidekiq-status web-client as it was proposed to use as a module for application workers, so we could merge these 2 PRs into one.

What do you think?

**Comment by kenaniah** [comment]
When I read the PR initially, I missed that the sorting was done on the Redis side. This would be a massive performance boost, and I would love to see this PR updated to work with the latest changes on master. 

Ping me again here and I'd be more than happy to review once ready. Thanks!

**Comment by kenaniah** [comment]
Looking into this a bit further, it looks like Redis `SORT` would be a great solution for sorting & pagination, but Redis doesn't allow list values to be expired individually. This means that the list can not be automatically cleaned up when job keys are expired, leading to a bloated sorting list (and potentially missing results due to expired keys). That said, list cleanup can be accomplished by using `ZADD` with the expiration timestamp as the score along with `ZREMRANGEBYSCORE` to remove expired values from the sorting list (garbage collection). Garbage collection could be run automatically from the Web UI.

**Comment by kenaniah** [comment]
I'll close this for now given the conflicting files and the updates that need to be made. Please feel free to reopen once conflicts are resolved. Thanks!

**Comment by mpospelov** [comment]
Ok sure will do it on this week, thanks for your notes

**Pull request closed without merging**
