### PR TITLE
feature/all_jobs_or_only_sidekiq_status_workers

### PR DESCRIPTION
**Pull request by brampey**
Changes to support having Sidekiq::Status only track the status of jobs specifically including Sidekiq::Status::Worker for use where only the status of certain jobs matter and to reduce the Redis memory usage.

### CODE REVIEW

**Comment by pramodshinde** [comment]
@brampey - Thank you for your PR, I will review these changes and merge if any issues let you know.

**Comment by pramodshinde** [comment]
@brampey - Can you resolve conflicts?

**Comment by brampey** [comment]
@pramodshinde :  Yes.  Thought I had already.  I'll take a look at this tomorrow.

**Comment by pramodshinde** [comment]
@brampey any updates on this?

**Comment by brampey** [comment]
No updates.  Conflicts resolved?

Bill Rampey
815-353-6494

**Comment by pramodshinde** [comment]
@brampey merge conflicts are not resolved yet.

**Comment by kenaniah** [comment]
Closing in favor of #113 as the more up-to-date PR

**Pull request closed without merging**
