### PR TITLE
upgrade /statuses view

### PR DESCRIPTION
**Pull request by mosasiru**
- add header sort
  - we can sort statuses by clicking headers
- add size option
  - we can see more than 25 statuses

### CODE REVIEW

**Comment by pramodshinde** [comment]
Can you make it one commit? So its easy to review and all changes seems related to Web UI? Make sure you test these changes thoroughly so it won't break any existing feature.

**Comment by mosasiru** [comment]
@pramodshinde 
This is a whole changes. https://github.com/utgarda/sidekiq-status/pull/77/files
I think the commit  should not be one commit because this pull-request includes two changes.

And all changes is only related to Web UI.

**Comment by pramodshinde** [comment]
@mosasiru -  Its okay to make it one commit even if change includes multiple files changes, since all changes is only related to Web UI, I would suggest to squash your commits to one commit as its same feature, use `git squash` command to this. If your are finding difficulties doing this let me know.

**Comment by mosasiru** [comment]
I meaned not two files commits but two functional commits, but I see your point. I squashed.

**Comment by pramodshinde** [comment]
@mosasiru Perfect! :+1:  I'll merge this after some testing at my side.

**Comment by mosasiru** [comment]
thank you!

**Pull request merged**
