### PR TITLE
Store custom payload alongwith the status

### PR DESCRIPTION
**Pull request by jigyasam**
I've tested this with our repo, already.

### CODE REVIEW

**Comment by utgarda** [comment]
Hi @jigyasam , thanks for participating. Sorry about the delay. If you need this functionality ( obviously, you do, cause you cared to implement it), I'll be glad to merge it and update the gem.

Also, I noticed your good dev style - rybydocs with the code, specs in place, readme updated. That's awesome! And, as everyone probably noticed, sidekiq-status needs a new maintainer for quite some time already. I didn't code in Ruby in years, by-and-by I'm becoming unfit for the task. If you're interested, let's talk this over, I'll give you write access to this repo, and if you treat it nicely for some time, I'll transfer the gem.

**Comment by jigyasam** [comment]
Hey @utgarda Thanks for getting back. It would be awesome to have this functionality merged in the gem and not have to use my fork for it.

As for helping out with this repo, I would love to. Ruby is first love for me, and has been for years. Let me know how we can take this forward.

**Comment by pramodshinde** [comment]
@utgarda, @jigyasam 

I think gem don't need such feature/functionality, Because it already gives the way to store custom payloads along with status. 
Here is way, as doc clearly explains use of `store` method from class `Sidekiq::Status::Worker` 

if you want to store payload say `payload = { any: "custom", hash: "object" }`, I do following 

```ruby
class MyJob
  include Sidekiq::Worker
  include Sidekiq::Status::Worker # Important!

  def perform(*args)
    # a way to associate data with your job
    data = { payload: { any: "custom", hash: "object" }}
    store data
  end
end
```

**Comment by jigyasam** [comment]
@pramodshinde Personally, I prefer a public API, which is `Sidekiq::Status` itself. Going around it to `include Sidekiq::Status::Worker` seems hackish, to me.

Besides, my specific problem is also an Integration with `ActiveJob`. `jid` here is the Sidekiq job ID, which is not readily available in `perform` if you use ActiveJob. I only have `ActiveJob'`s `job_id` and needed to map it to `Sidekiq`'s `jid`. In addition I preferred adding a public API as `Sidekiq::Status::update`.

**Comment by utgarda** [comment]
@jigyasam I can respect you need in this API update, even if it's somewhat redundand and it's functionality can be implemented otherwise. Could you somehow make at least some tests configurations pass? That pre-merge build failed all of them - all the combinations of Ruby and gem dependencies, every test config was shown red.

**Comment by pramodshinde** [comment]
@jigyasam Thank you for correcting me. 

@utgarda If you decide to merge after test fixes, @jigyasam I would suggest following change 
In lib/sidekiq-status/client_middleware.rb
```ruby
def active_job_id_present?(msg)
  # code goes here 
end 
```
Change above method name to 

```ruby
def has_active_job_id?(msg)
  # code goes here 
end 
```
Also, 
+ Don't need Minor version bump, that eventually @utgarda  will do while release if at all required.
+ @jigyasam - Can you confirm following:  
  + Once you map active `job_id` to `jid` and update `payload`, After that What if `status` of job with `jid` (sidekiq jid) gets updated, will `Sidekiq::Status::get_all(active_job_id)` return updated status using active_job_id or it will return only `jid` along with `payload`.

**Comment by jigyasam** [comment]
@utgarda Sorry, I was terribly caught up with something. I'll get the tests passing this weekend. They are all failing because I upgraded `sidekiq` version. 

@pramodshinde I like you suggestions, I'd push those changes next. And to clarify, I left the original Redis entry for job status as is. Essentially, you can simply do:

~~~ruby
status = Sidekiq::Status.get_all(active_job_id)
Sidekiq::Status.queued?(status['jid'])
Sidekiq::Status.complete?(status['jid'])
Sidekiq::Status.working?(status['jid'])
~~~

I've put in an example of Redis entries being written in Readme. Let me know if its still unclear :smile:

**Comment by utgarda** [comment]
@jigyasam @pramodshinde sure I'll merge when tests are fixed! And yeah, version bumps aren't that necessary, leave at least something for me to do :)

**Comment by kenaniah** [comment]
We now natively support ActiveJob, so `#store` and `#retrieve` should now solve your use case. I know this would still require including `Sidekiq::Status::Worker`, but I'd prefer not to introduce a duplicate API now that ActiveJob support is completed.

Could I ask you to test out the upcoming 0.7.0 release to see if this now meets your needs?

**Comment by kenaniah** [comment]
Closing this out as sidekiq-status no longer tracks job statuses for non-sidekiq-status workers.

**Pull request closed without merging**
